### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by Lucas-Marcel** [McDevon/taxman-engine#1]
I have no idea how to build it.

**Comment by McDevon** [comment]
This project contains the game engine files, which are platform-agnostic, and cannot be built alone.

To build, you need to port the engine to a platform. In order to run on a Playdate device, you can use the [Playdate platform project](https://github.com/mcdevon/taxman-playdate), which has this project as a subproject. It is also possible to run the engine on other platforms, including web using the [WASM platform project](https://github.com/mcdevon/taxman-wasm).

If you are having build issues with those projects, please open tickets there accordingly.
